"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ThunderSearch.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'LOGO.jpeg',
    'plist': {
        'CFBundleShortVersionString': '2.5.0',
        'NSHumanReadableCopyright': 'Copyright © 2023 xzajyjs All rights reserved.',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
