"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from ThunderSearch import VERSION

APP = ['ThunderSearch.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'LOGO.icns',
    'plist': {
        'CFBundleShortVersionString': VERSION,
        'NSHumanReadableCopyright': 'Copyright © 2023 xzajyjs All rights reserved.',
    },
    'arch': 'universal2'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
